services:
  app:
    image: ghcr.io/ralacerda/nuxt-oscar:latest
    ports:
      - "3000:3000"
    volumes: 
      - ./database:/app/database
    env_file:
      - ./.env
    command: ["node", "/app/server/index.mjs"]

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 30
